### ISSUE TITLE
本番環境でYouTubeAPIを動かしたい

### ISSUE THREAD

**Issue by mac042597** [mac042597/mukbang_asmr_search#21]
## 実現したいこと
herokuへデプロイ後、YouTube APIを叩き動画を取得したいです。
検索用語をクリックしAPIを叩くとエラーになります。

## 現状発生している問題・エラーメッセージ
開発環境ではAPIを叩くと正常に動画が取得され表示される。
[![Image from Gyazo](https://i.gyazo.com/f39f0d10ce1bb11fa6338412580b2832.jpg)](https://gyazo.com/f39f0d10ce1bb11fa6338412580b2832)

本番環境でAPIを叩くとエラーが発生。
[![Image from Gyazo](https://i.gyazo.com/570f560f3b3b9886ca7a46a38ace9529.png)](https://gyazo.com/570f560f3b3b9886ca7a46a38ace9529)

エラーログは以下の通りになります。
[![Image from Gyazo](https://i.gyazo.com/b84be4bc6e4e8b5d226d4ccb1c547930.jpg)](https://gyazo.com/b84be4bc6e4e8b5d226d4ccb1c547930)

## どの処理までうまく動いているのか
先述しましたが、開発環境では問題なく動いています。

herokuデプロイ後では、用語一覧表示までは動いています。
※各ボタン(日本語で探す、韓国語で探す）をクリックするとAPIと叩くアクションが動きます。
[![Image from Gyazo](https://i.gyazo.com/2aba025f6c7058f3db6b61dddcf3def7.png)](https://gyazo.com/2aba025f6c7058f3db6b61dddcf3def7)

## 該当のソースコード
#controllers/concerns/youtube.rb
```
module Youtube
  extend ActiveSupport::Concern

  require 'google/apis/youtube_v3'
  def search_movie(keyword)
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.key = Rails.application.credentials.google[:api_key]

    next_page_token = nil
    opt = {
      q: keyword,
      type: "video",
      max_results: 21,
      order: :relevance,
      page_token: next_page_token
    }

    youtube.list_searches(:snippet, **opt)
  end
end
```
#controllers/fonomatopoeia_searches_controller.rb
```
class OnomatopoeiaSearchesController < ApplicationController
  include Youtube

  def japanese_movies
    japanese_notation = params[:japanese_notation]
    @keyword = japanese_notation + " " + "モッパン"
    #binding.pry
    @japanese_movies = search_movie(@keyword)
  end

  def korean_movies
    korean_notation = params[:korean_notation]
    #binding.pry
    @keyword = korean_notation + " " + "먹방"
    @korean_movies = search_movie(@keyword)
  end
end
```
#controllers/food_searches_controller.rb
```
class FoodSearchesController < ApplicationController
  include Youtube

  def japanese_movies
    japanese_notation = params[:japanese_notation]
    @keyword = japanese_notation + " " + "モッパン"
    #binding.pry
    @japanese_movies = search_movie(@keyword)
  end

  def korean_movies
    korean_notation = params[:korean_notation]
    #binding.pry
    @keyword = korean_notation + " " + "먹방"
    @korean_movies = search_movie(@keyword)
  end
end

```

## エラーから考えられる原因
```
2022-09-05T14:03:19.254435+00:00 app[web.1]: F, [2022-09-05T14:03:19.254382 #4] FATAL -- : [9d665f32-bd7e-47a3-9318-a3c62e4cf593]
2022-09-05T14:03:19.254436+00:00 app[web.1]: [9d665f32-bd7e-47a3-9318-a3c62e4cf593] NoMethodError (undefined method `[]' for nil:NilClass
2022-09-05T14:03:19.254436+00:00 app[web.1]: 
2022-09-05T14:03:19.254437+00:00 app[web.1]: youtube.key = Rails.application.credentials.google[:api_key]
2022-09-05T14:03:19.254437+00:00 app[web.1]: ^^^^^^^^^^):
```
上記のエラーから、YouTube APIを使うためのAPI keyがうまく渡せていなかと考えました。

## 試したこと
下記参考記事を元に、herokuに変数を設定しました。
変数を設定してもエラーは治らず、 `heroku restart`で再起動を行いましたが変化がありませんでした。   
https://qiita.com/takemuu/items/7a093ea92b4562276745
https://teratail.com/questions/318281

**Comment by kerochelo** [comment]
@mac042597 
一旦本番のrails consoleでyoutube.keyが取得できるか確認するといいかもです

**Comment by mac042597** [comment]
@kerochelo 
本番のrails consoleでyoutube.keyが取得できるか確認したところ、
nilになりyoutube.keyが取得できていませんでした。
[![Image from Gyazo](https://i.gyazo.com/b7be7afe7ca9f8df8703d4d53f1f97f2.png)](https://gyazo.com/b7be7afe7ca9f8df8703d4d53f1f97f2)

`youtube = Google::Apis::YoutubeV3::YouTubeService.new`では
変数`youtube`が作成できているので、
`youtube.key = Rails.application.credentials.google[:api_key]`にて
api_keyが取得できていないのが原因でしょうか？

**Comment by kerochelo** [comment]
@mac042597 
`credentials`自体が何も入っていない感じかもですね
もしくは複合されてないのかも、secret_key_baseを使って複合するのでそれをHerokuで設定していたりします？

**Comment by mac042597** [comment]
@kerochelo
railsのsecret_key_baseの設定は何も触ってはいないです。

herokuの設定 Config Varsを確認したとことろ、SECRET_KEY_BASEというものが作成されていました。
[![Image from Gyazo](https://i.gyazo.com/5959f42329fe1f7a9b5afa7fd52357fc.png)](https://gyazo.com/5959f42329fe1f7a9b5afa7fd52357fc)
しかし、railsの`credentials.yml.enc`で確認したsecret_key_baseとは違う値が入っていたので
設定はされていないと考えます。

**Comment by kerochelo** [comment]
@mac042597 
それかも！
同じものにしないとcredentialsが複合できないのでエラーになっているかと！
ローカルにあるmaster_keyを環境変数で設定してみて、再度試してもらえますか？

**Comment by mac042597** [comment]
@kerochelo 
master.keyをherokuの環境変数としてセットしたところAPIが動きました😭🙌
```
heroku config:set RAILS_MASTER_KEY=`cat config/master.key`
```

[![Image from Gyazo](https://i.gyazo.com/2bfc578deabe41dbbd44a8cb1de0201e.png)](https://gyazo.com/2bfc578deabe41dbbd44a8cb1de0201e)

credentialsで登録した情報は暗号化されていて、master keyを復号化キーとしてデータを取得する。ローカルでは`config/master.key`にmaster keyを保管していたのでローカルでは問題なく動いたが、`config/master.key`は`.gitignore`で公開されないのでherokuではmaster keyが見つからず、API_keyが取得できなかった為、APIが作動しなかったということでしょうか…！

credentialsについて勉強不足でした。
ご教示いただきありがとうございました！
